### ISSUE TITLE
#13 #7でiPhone7以外のデバイスサイズへの対応後発生した表示崩れへの対応[バグ]

### ISSUE THREAD

**Issue by naoto77** [naoto1990/study_bolt#13]
## 作業内容
- #7の修正の結果、iPhone7, iPhone 7 Plusサイズで表示崩れが発生

## 完了条件
- iPhone7, iPhone 7 Plusサイズで表示崩れのバグが解消される

**Comment by naoto77** [comment]
## iPhone7, iPhone 7 Plusサイズで表示が崩れた原因を確認する
- ~おそらくVary for Traitsでのサイズクラスごとの設定方法が適切でなく、iPhone SEサイズの変更とぶつかり上書きされてしまったことが原因か？~
- ~正しくサイズクラスごとにレイアウトを設定する方法を確認し、実装する必要がある~
- 原因は、内部に複数の画面を抱えるContainer viewのwidth, heightのConstraintsが基準となるiPhone 7のサイズに合わせ固定値で設定されていたこと
  - 内部に抱える各画面のwidth, heighのConstraintsが、ScrollViewに対してEqualになっているため、そもそもContainer viewのwidth, heightは設定不要と思われる
    - Container viewのwidth, heightのConstraintsを削除しても問題は起きず、逆にiPhone 7 Plusのサイズでの表示崩れが解消された
  - width, heightのConstraintsが固定値になっている箇所に関して、少なくともContainer viewは固定値を削除する
  - その他ラベル等に関しては、別途確認し対応する
  - これにより、サイズクラスに関しては、Compact, Regularの組み合わせが異なるデバイスごとに設定するものであることがわかった

**Comment by naoto1990** [comment]
## iPhone7, iPhone 7 Plusサイズが基準のサイズのため、このサイズの崩れをまず修正
